#!/bin/sh

# sudo ./clean

echo "|||Show Storage of The Root|||"
echo "Filesystem      Size  Used Avail Use% Mounted on"
df -h  | grep /$ 
# du -Sh | sort -rh | head -n 10 # get the largest 10 direcotories
# df -h  | sort --key 5 -rh # sort according to the 5th column
echo "|||Show Storage of The Snaps|||"
df -h  | grep /snap | sort --key 3 -rh
#
#
echo "|||Check the Drive Space Used by Cached Files|||"
du -sh /var/cache/apt
#
echo "|||Clean all the log file|||"
logs=`find /var/log -type f`
for i in $logs
do
> $i
done
#
echo "|||Clear systemd journal logs|||"
journalctl --vacuum-time=3d
#
echo "|||Clean the thumbnail cache|||"
rm -rf ~/.cache/thumbnails/*
#
echo "|||Free up space by cleanning out the cached packages|||"
apt-get autoclean -y # remove only the outdated packages, like those superseded by a recent update
apt-get clean -y #  delete apt cache in its entirety -frees more disk space-
echo "|||Getting rid of partial packages|||"
apt-get remove --purge -y software-properties-common -y
#
echo "|||Getting rid of no longer required packages|||"
apt-get autoremove -y
#
echo "|||Remove Any Automatic Dependencies that are No Longer Needed with all of the associated configuration files from the dependencies|||"
apt-get --purge autoremove -y
#
echo "|||Getting rid of orphaned packages|||"
deborphan | xargs sudo apt-get -y remove --purge
#
#
echo "|||Remove the Trash|||"
rm -rf /home/*/.local/share/Trash/*/**
rm -rf /root/.local/share/Trash/*/**
#
echo "|||Remove Man|||"
rm -rf /usr/share/man/?? 
rm -rf /usr/share/man/??_*
#
echo "|||Delete all .gz and rotated file|||"
find /var/log -type f -regex ".*\.gz$" | xargs rm -Rf
find /var/log -type f -regex ".*\.[0-9]$" | xargs rm -Rf
#
echo "|||Cleaning the old kernels|||"
dpkg-query -l|grep linux-im*
apt-get purge $(dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | head -n -1) --assume-yes
apt-get install linux-headers-`uname -r|cut -d'-' -f3`-`uname -r|cut -d'-' -f4`
#
#
echo "|||Removes old revisions of snaps|||"
du -h /var/lib/snapd/snaps
echo "|||CLOSE ALL SNAPS BEFORE RUNNING THIS|||"
set -eu
#
echo "|||Retain only two old revisions of snaps|||" # starting from snap v2.34
sudo snap set system refresh.retain=2 

#
#
echo "|||Show Storage of The Root|||"
echo "Filesystem      Size  Used Avail Use% Mounted on"
df -h  | grep /$ 
echo "|||Show Storage of The Snaps|||"
df -h  | grep /snap | sort --key 3 -rh
#
#
#Cleaning is completed
echo "|||"Cleaning is completed"|||"
###
